version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

search:
  ranking:
    tests/*: -5
